### ISSUE TITLE
Is there a way to change the "start of week" day from Monday to Sunday?

### ISSUE THREAD

**Issue by 8bit-echo** [winexy/vue-renderless-calendar#11]
Looking through the docs and some of the code, I don't see anything about the day of the week that is at index: 0. In your example, the start of the week is on Monday, but I'm looking for a way to set it to be Sunday. Can you point me in the right direction?

**Comment by winexy** [comment]
Hi, unfortunately right now there is no such option. But i guess you might wanna contribute 🙂
